# source 'https://rubygems.org'

#gem 'rubocop', require: false
#gem 'getHtml', git: 'DmytroOnopa/RubyHW/HW3/getHtml'
#gem 'nokogiri'
gem 'getHtml', git: 'https://github.com/DmytroOnopa/RubyHW/', glob: 'getHtml/*.gemspec'